package pprnt

const (
	//ColorReset ...
	ColorReset string = "\033[0m"
	//ColorRed ...
	ColorRed string = "\033[31m" //Not supported or nil
	//ColorGreen ...
	ColorGreen string = "\033[32m" //String
	//ColorYellow ...
	ColorYellow string = "\033[33m" //Keys
	//ColorBlue ...
	ColorBlue string = "\033[34m" //Bool
	//ColorPurple ...
	ColorPurple string = "\033[35m" //Int floats
	//ColorCyan ...
	ColorCyan string = "\033[36m" //Brackets or Corch
	//ColorGray ...
	ColorGray string = "\033[37m"
	//ColorWhite ...
	ColorWhite string = "\033[97m"
)
